# Generated by Django 4.2.1 on 2023-05-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, verbose_name="Nomi")),
                ("slug", models.SlugField(max_length=255)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="product/category_images",
                        verbose_name="Categoriya rasimi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.category",
                        verbose_name="Ota kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoriya",
                "verbose_name_plural": "Categoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, verbose_name="Nomi")),
            ],
            options={
                "verbose_name_plural": "Xil(xususiyat)",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, verbose_name="Nomi")),
            ],
            options={
                "verbose_name": "Davlat",
                "verbose_name_plural": "Davlatlar",
            },
        ),
        migrations.CreateModel(
            name="Manufactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, verbose_name="Nomi")),
                ("description", models.TextField(verbose_name="Haqida")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.country",
                        verbose_name="Ishlab chiqligan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishlab Chiqqan Zavod",
                "verbose_name_plural": "Ishlab Chiqqan Zavodlar",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "sale_count",
                    models.IntegerField(default=0, verbose_name="Sotilganlar soni"),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Ko'rganlar soni"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Holati Aktiv"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.category",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.country",
                        verbose_name="Ishlab chiqligan davlat",
                    ),
                ),
                (
                    "manufactory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufactory_re",
                        to="product.manufactory",
                        verbose_name="Ishlab chiqqan Korxona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(max_length=255, verbose_name="O'lchov birligi"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=17, verbose_name="Narxi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Holati Aktiv"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_price",
                        to="product.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mahsulot Narxlari",
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        null=True,
                        upload_to="product/product_images",
                        verbose_name="Video/Rasm",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Holati Aktiv"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_media",
                        to="product.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mahsulot Video/rasmlari",
            },
        ),
        migrations.CreateModel(
            name="ProductCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.character",
                        verbose_name="Mahsulot xususiyati",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_character",
                        to="product.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mahsulot xususiyati",
            },
        ),
    ]
