# Generated by Django 4.2.1 on 2023-05-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Xarajot nomi")),
            ],
        ),
        migrations.CreateModel(
            name="OutlayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Xarajotlar kategoriyasi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd pul"),
                            ("card", "Cartadan"),
                            ("bank", "Bank"),
                        ],
                        max_length=255,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("income", "Tavar krimi"),
                            ("order", "Zakaz"),
                            ("client", "Xaridor"),
                            ("provider", "Yetkazib beruvchi"),
                            ("outlay", "Xarajat"),
                        ],
                        max_length=255,
                        verbose_name="To'lov turi",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Krim"), ("outcome", "Chiqim")],
                        max_length=50,
                        verbose_name="Tranzaksiya turi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=17, verbose_name="Qiymati"
                    ),
                ),
                ("is_deleted", models.BooleanField(verbose_name="O'chirilgan")),
                ("comment", models.CharField(max_length=400, verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="O'chirilgan sana"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client.client",
                        verbose_name="Xaridor",
                    ),
                ),
            ],
        ),
    ]
